# This is a basic workflow to help you get started with Actions

name: Hello World
on: workflow_dispatch
jobs:
  build: 
    runs-on:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ubuntu-latest                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         cancel-timeout-minutes: 
    steps:
      - name: hellow step
        run: |
         echo "welcome to GHA1"
         echo "Welcome to GHA2"
  test:
    run-on: ubantu-latest
    steps:
      - name: hellow step
        run: echo "welcome to GHA3"
  Deploy:
    run-on:
    steps:
      - name: hellow step
        run: echo "welcome to GHA4"
      
      
        
  
    


  
  

      
      
  
